### PR TITLE
Stops manipulate the items attribute itself to render HTML in SOY template #7

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by fernandosouza** [comment]
cc @brunobasto

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @fernandosouza, I think we can improve this by using the new `prepareStateForRender` so that we can change the Soy template parameter from `internalItems` back to `items`. This makes for a nicer API when rendering from the server.

**Comment by brunobasto** [comment]
Reference: https://github.com/metal/metal.js/pull/181

**Comment by fernandosouza** [comment]
It makes total sense. I'm going to develop the changes.

**Comment by fernandosouza** [comment]
Branch updated @brunobasto

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
