### PR TITLE
Adds keys attribute

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by brunobasto** [comment]
@fernandosouza, I don't think that should be exposed. We should handle that automatically somehow. It's weird that we ask the users of the component for something so specific like that.

**Comment by fernandosouza** [comment]
I've chosen to expose this option for the user because the developer can guarantee a unique value for it, passing the ID of a database table for example. The only required data we have in `select component` to deal with it is the` items` attribute, which is the `labels` of the `dropdown` menu. It is not common, but it can have duplicated values. In a list of cities, for example, a country may have more than one city with the same name.

We can have a method for generating the array of `keys` using the `values` attribute, but this attribute is not required. The developer may choose don't provide it.

**Comment by fernandosouza** [comment]
@brunobasto, I suggest making it simple for now and don't auto-generate those keys. But if you really think it will be better we have this feature in the component it's better to wait for this PR https://github.com/metal/metal-select/pull/10 because we may use `items` attribute as an array of strings to use for generating those keys.

**Comment by jbalsas** [comment]
I'm closing this for now since it's not clear if we want to expose this or not...

**Pull request closed without merging**
